name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        libfranka-version: ['0.8.0']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libeigen3-dev libpoco-dev g++-7 gcc-7
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 10
        python -m pip install --upgrade pip
        python -m pip install pytest pybind11

    - name: Install specific libfranka version
      run: |
        git clone --recursive https://github.com/frankaemika/libfranka
        cd libfranka
        git checkout ${{ matrix.libfranka-version }}
        git submodule update
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_TESTS=OFF ..
        cmake --build .
        sudo cmake --install .

    - name: Install pybind11
      run: |
        git clone https://github.com/pybind/pybind11.git
        cd pybind11
        mkdir build
        cd build
        cmake .. -DPYBIND11_TEST=OFF
        make
        sudo make install

    - name: Set Environment Variables
      run: |
        echo "CMAKE_PREFIX_PATH=/usr/local:/usr/local/share/cmake/pybind11" >> $GITHUB_ENV
        echo "Franka_DIR=/usr/local/lib/cmake/Franka" >> $GITHUB_ENV
        echo "pybind11_DIR=/usr/local/share/cmake/pybind11" >> $GITHUB_ENV

    - name: Install pyfranka
      run: |
        export CMAKE_PREFIX_PATH=/usr/local:/usr/local/share/cmake/pybind11
        export Franka_DIR=/usr/local/lib/cmake/Franka
        export pybind11_DIR=/usr/local/share/cmake/pybind11
        pip install -e .

    - name: Debugging information
      run: |
        echo "G++ version:"
        g++ --version
        echo "GCC version:"
        gcc --version
        echo "Installed packages:"
        dpkg -l

    - name: Run tests
      run: pytest
