name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        libfranka-version: [0.7.0, 0.8.0, 0.9.0]  # Specify the versions you want to test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'  # Specify your desired Python version

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libeigen3-dev
        python -m pip install --upgrade pip
        python -m pip install .

    - name: Install specific libfranka version
      run: |
        git clone https://github.com/frankaemika/libfranka.git
        cd libfranka
        git checkout v${{ matrix.libfranka-version }}
        mkdir build
        cd build
        cmake ..
        make
        sudo make install
        cd ../..
        sudo rm -rf libfranka

    - name: Run tests
      run: |
        python -m pip install pytest
        pytest

