name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        libfranka-version: ['0.8.0', '0.9.0']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libeigen3-dev libpoco-dev
        python -m pip install --upgrade pip

    - name: Install specific libfranka version
      run: |
        git clone --recurse-submodules https://github.com/frankaemika/libfranka.git
        cd libfranka
        git checkout ${{ matrix.libfranka-version }}
        # Add missing include for <string> and <stdexcept>
        sed -i '7i#include <string>' include/franka/control_tools.h
        sed -i '7i#include <stdexcept>' src/control_types.cpp
        # Add necessary includes for GetCartesianLimit and SetFilters
        sed -i '9i#include <research_interface/robot/service_types.h>' src/robot_impl.h
        sed -i '10i#include <research_interface/robot/service_types.h>' src/robot.cpp
        mkdir build
        cd build
        cmake ..
        make
        sudo make install
        cd ../..
        sudo rm -rf libfranka

    - name: Set CMAKE_PREFIX_PATH
      run: echo "CMAKE_PREFIX_PATH=/usr/local" >> $GITHUB_ENV

    - name: Install Python dependencies
      run: python -m pip install .

    - name: Run tests
      run: |
        python -m pip install pytest
        pytest
